[profile.default]
src = "src"
out = "out"
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]

# Allow reading from broadcast directory for DevOpsTools
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
